command:
- "python"
- "app.py"

env:
- name: "SPACE_ID"
  value: "01f03517dd2d1b5181c6859d434de2aa"
- name: "SERVING_ENDPOINT_NAME"
  valueFrom: "https://adb-984752964297111.11.azuredatabricks.net/serving-endpoints/genie_check/invocations"