command:
- "python"
- "app.py"

env:
- name: "SPACE_ID"
  value: "xxxxxx"
- name: "SERVING_ENDPOINT_NAME"
  value: "genie_check"
- name: "GENIE_LOG_TABLE"
  value: "xxxxxxx.genie_conversation_logs"
- name: "DATABRICKS_SQL_HTTP_PATH"
  value: "/xxxxxxx"

  
